### ISSUE TITLE
[1.17.x] [Bug] Causes a lot of issues when disabling things in the config. 

### ISSUE THREAD

**Issue by ruvaldak** [kwpugh/EmeraldTools#10]
Seems to break fabric's tool lists when disabling things in the configs, and also seems to throw a bunch of errors about parsing.

[errors.log](https://github.com/kwpugh/EmeraldTools/files/6859645/errors.log)

It seems that disabling things in the config actually removing the tools causes a whole bunch of problems that can cause several mods to break, such as causing FallingTree to no longer detect axes.

**Comment by kwpugh** [comment]
Can you post a link to your current config for Emerald Tools please.

There is nothing I can do about the error messages when items are disabled, and they are harmless.  Its just letting you know things are missing.

Disabling items shouldn't do any harm to other mods though.  I need to look into that.

**Comment by ruvaldak** [comment]
Just double checked and indeed, re-enabling the tools I disabled fixed FallingTrees and allows trees to be chopped again. Disabling them prevents FallingTrees from working at all, even with fully vanilla tools such as an iron axe.

`{
	/* 
	   
	   
	   ******************************
	   EXTRA TOOLS
	   Paxels, Hammers,
	   Excavators, & TreeAxes
	   ******************************
	*/
	"enableHammers": false,
	"enableExcavators": false,
	"enablePaxels": false,
	"enableTreeAxes": false,
	"enableBows": false,
	/* 
	   
	   
	   ******************************
	   SETS
	   Armors, Tools, & Weapons
	   ******************************
	*/
	"enableEmeraldSet": true,
	"enableRubySet": false,
	"enableSteelSet": true,
	"enableObsidianSet": true,
	"enableCoppperSet": true,
	"enableAmethystSet": true,
	/* 
	   
	   
	   ******************************
	   AMETHYST TOOL MATERIAL
	   ******************************
	*/
	"amethystDurability": 840,
	"amethystMiningSpeed": 8.0,
	"amethystAttackDamage": 1.5,
	"amethystMiningLevel": 3,
	"amethystEnchantability": 25,
	"amethystEnableSilkTouch": true,
	"amethystEnableInfinity": true,
	"amethystEnableUnbreakable": true,
	/* 
	   
	   
	   ******************************
	   AMETHYST ARMOR MATERIAL
	   ******************************
	*/
	"amethystDurabilityMultiplier": 29,
	"amethystArmorEnchantability": 10,
	"amethystToughness": 2.0,
	"amethystKnockbackResistance": 0.5,
	/* 
	   
	   
	   ******************************
	   COPPER TOOL MATERIAL
	   ******************************
	*/
	"copperDurability": 250,
	"copperMiningSpeed": 5.5,
	"copperAttackDamage": 1.5,
	"copperMiningLevel": 3,
	"copperEnchantability": 18,
	/* 
	   
	   
	   ******************************
	   COPPER ARMOR MATERIAL
	   ******************************
	*/
	"copperDurabilityMultiplier": 24,
	"copperArmorEnchantability": 4,
	"copperToughness": 1.0,
	"copperKnockbackResistance": 0.5,
	/* 
	   
	   
	   ******************************
	   EMERALD TOOL MATERIAL
	   ******************************
	*/
	"emeraldDurability": 725,
	"emeraldtMiningSpeed": 8.0,
	"emeraldAttackDamage": 3.0,
	"emeraldMiningLevel": 3,
	"emeraldEnchantability": 10,
	/* 
	   
	   
	   ******************************
	   EMERALD ARMOR MATERIAL
	   ******************************
	*/
	"emeraldDurabilityMultiplier": 26,
	"emeraldArmorEnchantability": 12,
	"emeraldToughness": 2.0,
	"emeraldKnockbackResistance": 0.0,
	/* 
	   
	   
	   ******************************
	   RUBY TOOL MATERIAL
	   ******************************
	*/
	"rubyDurability": 960,
	"rubyMiningSpeed": 8.0,
	"rubyAttackDamage": 3.0,
	"rubyMiningLevel": 3,
	"rubyEnchantability": 10,
	/* 
	   
	   
	   ******************************
	   RUBY ARMOR MATERIAL
	   ******************************
	*/
	"rubyDurabilityMultiplier": 29,
	"rubyArmorEnchantability": 12,
	"rubyToughness": 2.0,
	"rubyKnockbackResistance": 0.0,
	/* 
	   
	   
	   ******************************
	   STEEL TOOL MATERIAL
	   ******************************
	*/
	"steelDurability": 512,
	"steelMiningSpeed": 7.0,
	"steelAttackDamage": 2.0,
	"steelMiningLevel": 3,
	"steelEnchantability": 9,
	/* 
	   
	   
	   ******************************
	   STEEL ARMOR MATERIAL
	   ******************************
	*/
	"steelDurabilityMultiplier": 21,
	"steelArmorEnchantability": 9,
	"steelToughness": 1.0,
	"steelKnockbackResistance": 0.5,
	/* 
	   
	   
	   ******************************
	   OBSIDIAN TOOL MATERIAL
	   ******************************
	*/
	"obsidianDurability": 650,
	"obsidianMiningSpeed": 5.5,
	"obsidianAttackDamage": 1.5,
	"obsidianMiningLevel": 3,
	"obsidianEnchantability": 4,
	/* 
	   
	   
	   ******************************
	   OBSIDIAN ARMOR MATERIAL
	   ******************************
	*/
	"obsidianDurabilityMultiplier": 24,
	"obsidianArmorEnchantability": 4,
	"obsidianToughness": 1.0,
	"obsidianKnockbackResistance": 0.5,
	/* 
	   
	   
	   ******************************
	   RUBY STEEL SWORD MATERIAL
	   ******************************
	*/
	"rubySteelDurability": 1102,
	"rubySteelMiningSpeed": 8.0,
	"rubySteelAttackDamage": 3.0,
	"rubySteelMiningLevel": 3,
	"rubySteelEnchantability": 12
}`

**Comment by kwpugh** [comment]
[EmeraldTools-Fabric-1.17.1-1.2.22.jar.zip](https://github.com/kwpugh/EmeraldTools/files/6859746/EmeraldTools-Fabric-1.17.1-1.2.22.jar.zip)

Can you try this build to confirm works with FallingTrees mod?

**Comment by ruvaldak** [comment]
> [EmeraldTools-Fabric-1.17.1-1.2.22.jar.zip](https://github.com/kwpugh/EmeraldTools/files/6859746/EmeraldTools-Fabric-1.17.1-1.2.22.jar.zip)
> 
> Can you try this build to confirm works with FallingTrees mod?

Works now.

**Comment by kwpugh** [comment]
Good.

So I can't do anything about all the warning messages about missing recipes for items that are disabled.  I will ask around, but I think it is just the way of things.

Were there any others mods that were affected by this?

**Comment by kwpugh** [comment]
All those warnings are because the game is still reading through all the JSON model and recipes files and reporting back that the referenced items are not registered in the game.

What broke FallingTree was the fact that my JSOn that added my axes (including the disabled ruby axe) were not set to required=false.  Once I changed that, things were fine.   Minecraft has a habit of reading its JSON for tool types and if one is missing, it simple skips the file entirely and skips its own.  Very touchy.  So no tools got tagged as AXES.

**Comment by ruvaldak** [comment]
I haven't found anything else that had issues, but if I run across anything, I will post here. Might be worth double checking to make sure other tools are set to required=false, as well, just to avoid any possible issues down the line.

**Comment by kwpugh** [comment]
I set them for all of the tool types in the mod.
