### ISSUE TITLE
[1.17.1] more gems and easy emerald tools ruby paxel problem

### ISSUE THREAD

**Issue by urolithicrogue** [kwpugh/EmeraldTools#12]
i have both mods installed but i am unable to make ruby paxels because one tool comes from more gems while the others come from your easy emerald tools mod. i didn't see an option to enable compatibility between the two mods. not sure if this is a problem with any of the other tools

yes this is on a server, i was not sure which mod to post this under since it is related to both mods and you are the author of both mods

i am using adapaxels but as far as i can tell none of the issues are related to that mod that i know of

**Comment by kwpugh** [comment]
the recipes are different.   they use axe, pickaxe, shovel from their own mods.  Check to make sure you aren't mixing items in the recipe.   I just checked and they are both able to be able to be made.

**Comment by kwpugh** [comment]
they are not compatible with each other.

**Comment by kwpugh** [comment]
If you are having trouble making specific recipes when there are dups, you need to use:  https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

**Comment by kwpugh** [comment]
![Screen Shot 2021-09-27 at 9 38 23 AM](https://user-images.githubusercontent.com/8809210/134930370-2d3f1f68-fdf5-4fa2-9c35-d2e8f545c1df.png)

**Comment by kwpugh** [comment]
should be addressed by recipe conflict mod as show above.
