### ISSUE TITLE
[1.18.2] Copper shears don't shear

### ISSUE THREAD

**Issue by kingstairs** [kwpugh/EmeraldTools#16]
MC 1.18.2, ET 1.3.38, Fabric
New game. Made some copper shears, and they don't shear sheep. Soon afterward made _iron_ shears, and they _did_ shear sheep.
Totally game-ruining! ;-)

Didn't see any errors or messages in the log.
I'm guessing the shears are simply missing a property/tag for shearing.
I am using other mods (will provide full list if needed), but I don't think any of the others affect copper/tools (Gobber2 maybe?).
Thank you.

**Comment by kwpugh** [comment]
Yeah, those are broken, I thought I had disabled them.  Sorry about that.

**Comment by kwpugh** [comment]
I'm removing the shears  from the mod, more trouble than it is worth.
