### ISSUE TITLE
[1.18.2] can't craft emerald tools

### ISSUE THREAD

**Issue by louisdoran1234** [kwpugh/EmeraldTools#17]
I'm on version 1.3.37 of emerald tools and version 0.13.3 on fabric
for some reason I can't craft the emerald tools and there are no recipes for them that show up

**Comment by kwpugh** [comment]
please post a copy of your latest.log from the /logs folder.

**Comment by kwpugh** [comment]
Are you using REI for the recipes?  If so, which version of REI are you using?

**Comment by louisdoran1234** [comment]
[latest.log](https://github.com/kwpugh/EmeraldTools/files/8240383/latest.log)
this is a modpack btw

**Comment by kwpugh** [comment]
Can you post a copy of the emerald tools config file from the modpack?

**Comment by louisdoran1234** [comment]
where would I find that

**Comment by louisdoran1234** [comment]
[general.zip](https://github.com/kwpugh/EmeraldTools/files/8240394/general.zip)

**Comment by kwpugh** [comment]
Not sure what that is, but cannot open it.  Config is here.
![Screen Shot 2022-03-13 at 1 50 19 PM](https://user-images.githubusercontent.com/8809210/158074649-1988e8ed-2d5e-4da4-bd91-799230fdb5a1.png)

tried REI and Emerald Tools on 1.18.1

![Screen Shot 2022-03-13 at 1 48 39 PM](https://user-images.githubusercontent.com/8809210/158074658-7d71a19a-7c56-441d-b2b4-d142fd921bb8.png)

**Comment by louisdoran1234** [comment]
I can't upload a json file

**Comment by kwpugh** [comment]
zip it

**Comment by kwpugh** [comment]
or post it to gist.

https://gist.github.com

**Comment by kwpugh** [comment]
I'm not seeing any error in the latest.log, so nothing there.

Did you build the modpack?

**Comment by louisdoran1234** [comment]
no i found it on forge, also the file keeps corrupting, you got discord?

**Comment by kwpugh** [comment]
https://discord.gg/6B3wJQQa

**Comment by kwpugh** [comment]
I don't do new friends with all the scams these days.

you can come to my support Discord.

**Comment by louisdoran1234** [comment]
i put it in fabric mod help
