### ISSUE TITLE
[1.18.2] Armor knockback resistance values

### ISSUE THREAD

**Issue by mpustovoi** [kwpugh/EmeraldTools#18]
Hello.
I've noticed that both the default and custom knockback resistance values from the config aren't showing up in the game, as it should be like with netherite armor. I tried to change, for example, from 0.1 to 1, but nothing.
I'm using latest version 1.3.39
I tried to attach a screenshot with the default knockback resistance and custom armor hardness values in config.
![Screenshot 2022-03-16 203232](https://user-images.githubusercontent.com/92390626/158654274-a7ed9a8c-3547-4e3d-bb7b-a8abab703b52.png)

**Comment by kwpugh** [comment]
<img width="749" alt="Screen Shot 2022-03-16 at 4 19 04 PM" src="https://user-images.githubusercontent.com/8809210/158693475-070ab039-c37d-410a-b078-c073ff7237f1.png">

Will  be fixed up in the next update.
