### ISSUE TITLE
[1.18.2] Suggestion for the possibility of changing armor values

### ISSUE THREAD

**Issue by mpustovoi** [kwpugh/EmeraldTools#19]
Hi again.
When I switched from Forge to Fabric, I found that the Fabric version of your mod lacked the ability to change how many armor points helmets, breastplates, greaves, and boots add.
Although your "Gobber" mod on Fabric has the ability to change armor stats. It would be nice to have such an opportunity here if it's possible.
I apologize if the translation is sloppy.
I'm using latest version 1.3.39

**Comment by kwpugh** [comment]
I will add  this to the next release.
