### ISSUE TITLE
[1.18.2] Ruby-Steel Sword stats

### ISSUE THREAD

**Issue by mpustovoi** [kwpugh/EmeraldTools#20]
With different values in the config, the damage and durability indicators of the Ruby-Steel Sword are similar to the regular Ruby Sword.
I'm using latest version 1.3.39
![Screenshot 2022-03-16 210213](https://user-images.githubusercontent.com/92390626/158658740-1a279c38-0aeb-4531-a81b-96bc3e9b1bda.png)
Values in the config at the moment:
![Screenshot 2022-03-16 210406](https://user-images.githubusercontent.com/92390626/158658771-1b726ab6-b591-4970-836d-943d5e029f21.png)

**Comment by kwpugh** [comment]
Ruby-Steel simply  adds the unbreakable tag, same stats.

Oh, the stats, yeah, let me look at that.

**Comment by kwpugh** [comment]
I found the  issue, will be fixed  in next release.
