### ISSUE TITLE
[1.18.1] Using Hammer on incorrect block type kicks user from server

### ISSUE THREAD

**Issue by chance633** [kwpugh/EmeraldTools#21]
Server is Fabric with loader 0.13.3
MC version 1.18.1
Emerald Tools - Fabric - 1.18.1-1.3.37

Issue does not generate any messages in server log file, kicks user and MC process closes. User are loading via technic launcher

Breaking any non-stone block (E.I. Grass, Sand, etc.) will cause the issue to appear. 

Log attached. All users experience this issue, logs show user ALargeMealworm experiencing the kick.
[2022-03-17-1.log](https://github.com/kwpugh/EasyEmerald/files/8306262/2022-03-17-1.log)

**Comment by kwpugh** [comment]
Which version of Mod  and Forge?    Need a system/crash log to do anything with this

**Comment by kwpugh** [comment]
Try without  Better  Nether.

**Comment by kwpugh** [comment]
I put a fix into the 1.18.2 version to get around the Better Nether issue.

**Comment by kwpugh** [comment]
Easy Emerald is supported for 1.16.5 and 1.18.2.   1.18.1 is out-of-date.

**Comment by kwpugh** [comment]
There  is a  fixed version for 1.18.1 now.  https://www.curseforge.com/minecraft/mc-mods/simple-emerald-tools-fabric/files/3701840
