### ISSUE TITLE
[Feature Request] Special Tool with (Wood, Stone, Iron, Diamon, Netherite)

### ISSUE THREAD

**Issue by ardissaps** [kwpugh/EmeraldTools#24]
Would be great if we can have missing tool from your special tool (Excavator, Hammer, Paxel, Bow, Tree Axe) with crafted material like Vanilla tool (stone, iro, diamond, netherite). Example all your tool are many but no Stone Bow, Iron Bow, Diamond Bow, Netherite Bow  and other special tool etc.
Thx in advance for making this great mod! Have a nice day!

**Comment by kwpugh** [comment]
I felt like there are enough choices for bows, so I was not going to add them.
