### ISSUE TITLE
io.netty.handler.codec.DecoderException: The received encoded string buffer length is less than zero! Weird string!

### ISSUE THREAD

**Issue by Gamerbolts** [kwpugh/EmeraldTools#26]
Hello! I am experiencing an issue and it only happens when I have Emerald Tools/Cloth Config API, Create and Spice of Fabric installed.

Fabric 1.18.2 - 0.14.7

EmeraldTools v1.3.43
Cloth Config v6.2.62
Create v0.4.1+601
Spice of Fabric v1.5.2
Fabric API v0.55.1

[latest.log](https://github.com/kwpugh/EmeraldTools/files/8878722/latest.log)

When I go to create the world it loads to 100% and then goes to a black screen with the message that I posted in the Subject line. I have tried all combinations of mods and it is only when they are all installed that I get the error. I have posted this on 3 githubs. Any help is appreciated. Thank you!

**Comment by kwpugh** [comment]
it is a conflict with nbtcrafting mod.  Spice of Fabric uses it as an embedded lib.  eliminate emerald tools or spice pf fabric.

**Comment by Gamerbolts** [comment]
OK will do. I did post this on spice of fabric's github too so maybe they'll be able to fix.

**Comment by kwpugh** [comment]
This is no longer an issue in 1.19.2
