### ISSUE TITLE
[1.19] Emerald Tools mod Axe does not have an "axe" tag?

### ISSUE THREAD

**Issue by lospejos** [kwpugh/EmeraldTools#28]
I'm not sure if this is an `Emerald Tools` issue and I'm not an expert in Minecraft mods, so sorry if I'm wrong.

I have `Emerald Tools` mod (`EmeraldTools-Fabric-1.19.0-1.4.13`), also I have `Falling Tree` mod (`FallingTree-1.19-3.6.1`) installed both together.
When I chop trees using stone axe from vanilla Minecraft, trees are falling as expected.
When I chop trees using `Copper Axe` from Emerald Tools, trees are not falling. I could of course add axes from `Emerald Tools` to allowed tools list in `Falling Tree` mod settings.

`Falling Tree` mod have hint in its settings: `Tools with "axe" tag will be automatically added to allowed tools list`
So I assumed that axes from `Emerald Tools` does not have `axe` tag properly set. Please check it and fix if required.

This also could be an issue of `Falling Trees` mod for sure.

**Comment by kwpugh** [comment]
The fabric "standard is "axes", tags like items should be plural.

<img width="424" alt="Screen Shot 2022-06-16 at 12 17 44 PM" src="https://user-images.githubusercontent.com/8809210/174129328-cfd7b5cf-d6ad-429d-8730-3054226763ed.png">

My axes are already listed.

In fact, if they are not in  the list, they won't work as axes in Fabric.

**Comment by kwpugh** [comment]
It looks like the Harvester code simply checks if it is an AxeItem, which mine are.  Something else may be going on.

![Screen Shot 2022-06-16 at 1 00 22 PM](https://user-images.githubusercontent.com/8809210/174137593-ab7ab0e1-2814-4212-916d-51b11fc28a1c.png)

**Comment by lospejos** [comment]
BTW I checked axes from `More Gems` mod (I assume it's also is your mod just like `Emerald Tools`), f.e. `Sapphire Axe`, and these axes work as expected with `Falling Tree` mod.

**Comment by kwpugh** [comment]
I fired up the mod and looked at its config, it automatically picked up all of my axes.

![Screen Shot 2022-06-16 at 1 18 47 PM](https://user-images.githubusercontent.com/8809210/174139002-e78bd594-6e43-4686-9804-7f677072a272.png)

What does your file look like?

**Comment by lospejos** [comment]
Didn't get what exactly file and in which mod should I check? Could you please specify exact mod name and file name which I should check? Thanks

**Comment by kwpugh** [comment]
in the folder where you minecraft instance is installed.

![Screen Shot 2022-06-16 at 1 57 09 PM](https://user-images.githubusercontent.com/8809210/174144996-ceb722a9-b7bc-4f92-810d-dccc27708c96.png)

BTW: with my basic setup, all of the axes work fine at harvesting

**Comment by lospejos** [comment]
OK, may be there is some misunderstanding:
I use mod `FallingTree` (see https://www.curseforge.com/minecraft/mc-mods/falling-tree) to chop whole trees, and you (I suppose) do mention `Tree Harvester` mod (https://www.curseforge.com/minecraft/mc-mods/tree-harvester-fabric).
They are different mods. I don't use `Tree Harvester`.

**Comment by kwpugh** [comment]
My bad.  I will try FallingTree.   According to the author it automatically picks up tools that extend AxeItem, which mine do.

**Comment by kwpugh** [comment]
I just tested my mods (EmeraldTools, MoreGems, Gobber) and all the axes work fine with FallingTree.

**Comment by kwpugh** [comment]
The tree axes work as well.

**Comment by lospejos** [comment]
Thanks, may be it's an issue in my mod setup or mods combination.

**Comment by lospejos** [comment]
I've tested it on a reduced amount of mods (only they was installed):
```
architectury-5.7.27-fabric.jar
cloth-config-7.0.72-fabric.jar
EmeraldTools-Fabric-1.19.0-1.4.13.jar
fabric-api-0.56.0+1.19.jar
FallingTree-1.19-3.6.0.jar
modmenu-4.0.0.jar
MoreGems-Fabric-1.19.0-1.4.19.jar
notenoughcrashes-4.1.6+1.19-fabric.jar
RoughlyEnoughItems-9.0.489.jar
```
and everything was fine.

It seems, some other mod breaks this behavior.  Thanks.
