### ISSUE TITLE
Add the ability to disable items

### ISSUE THREAD

**Issue by purejosh** [kwpugh/EmeraldTools#30]
With my server, I'm personally not a fan of paxels, tree axes, and excavators. Please add the ability for us to disable the crafting recipes for all types of items in the configuration .json.

**Comment by kwpugh** [comment]
You do that with data packs now

**Comment by purejosh** [comment]
How/where do I get that from?

**Comment by purejosh** [comment]
If you mean by using a recipe datapack to make the materials air and the resultant item a barrier block, that's not removing the item, that's making it uncraftable. It will still show in REI and the like.

**Comment by kwpugh** [comment]
when mojang added the registry freeze, disabling items/blocks via config is no longer recommended.  Disabling via datapack or KubeJS is preferred.

**Comment by kwpugh** [comment]
I don't have a pre-made datapack for that mod.  you can make it yourself or wait until I make one.

**Comment by kwpugh** [comment]
Are you using 1.18.2 or 1.19?

**Comment by purejosh** [comment]
1.18.2. We'll be updating to 1.19 in about 2 weeks, just waiting for mods to be stable.

**Comment by purejosh** [comment]
I can use KubeJS to block the recipes.
