### ISSUE TITLE
[1.19.1] Add a "nerf treeaxe/excavator/hammer" option

### ISSUE THREAD

**Issue by purejosh** [kwpugh/EmeraldTools#31]
I used to have custom made hammers that would lose durability at a per block broken level, and I would like to either lower the treeaxe/hammer/excavator durability by roughly 75%, or maybe have a config option that allows for "nerf mode", where it doesn't lose durability by the use, it loses durability by the block broken count. 

Calculating blocks broken could be hard, though, since using a hammer can break anywhere from 1 to 9 blocks, using an excavator is the same, using a treeaxe could break who knows how many. Maybe instead of trying to calculate the blocks broken, we can just set an additional modifier in the config for a percentage reduction on those three items separately? 

For example: 
```
	   ******************************
	   AMETHYST TOOL MATERIAL
	   ******************************
	*/
	"amethystDurability": 640,
	"amethystHammerDurabilityModifier": 30,
	"amethystExcavatorDurabilityModifier": 40,
	"amethystTreeaxeDurabilityModifier": 60,
	"amethystMiningSpeed": 6.0,
	"amethystAttackDamage": 1.5,
	"amethystMiningLevel": 3,
	"amethystEnchantability": 25,
	"amethystEnableSilkTouch": true,
	"amethystEnableInfinity": true,
	"amethystEnableUnbreakable": true,
	/* 
```
So, Hammers would be 30% less than 640, as an example. Or, you could use hard coded values here that default to the main durability, but we could update them to be whatever values we want.

**Comment by kwpugh** [comment]
I have this working in  dev.  still more testing is required, but it is looking very good.

hammer and excavator is done.

Treeaxe is going to be challenging,

**Comment by kwpugh** [comment]
added feature for block-for-block durability loss to the latest 1.19.1 versions of Gobber, Emerald Tools, MoreGems, and Treeaxes.

**Comment by purejosh** [comment]
Wow, I'm blown away that it was so easy for you. Thank you so much!
