### ISSUE TITLE
Why is Pugh Tools private/closed source?

### ISSUE THREAD

**Issue by ruvaldak** [kwpugh/EmeraldTools#33]
I'm wanting to do a backport of the latest 1.19.2 changes to 1.18.2 on my fork and realized that Pugh Tools is private and/or closed source. I can put the jar in loom-cache to compile, but the version used in your 1.18.2 release (pugh tools 1.2.7) is outdated and doesn't support the latest features added in 1.19.2, while 1.3.17 doesn't work at all on 1.18.2, and I have no way of attempting to backport it without the source code.

**Comment by kwpugh** [comment]
It is closed source because I do not want others using it at this point.
