### ISSUE TITLE
Amethyst Pickaxe stacks Silk Touch enchantments upon repair

### ISSUE THREAD

**Issue by SomeOldOakTree** [kwpugh/EmeraldTools#34]
Whenever repairing an amethyst pickaxe in the crafting grid with an amethyst shard, a new instance of the "Silk Touch" enchantment is added to the pick.

i.e. if the pick were repaired 5 times, the listed enchantments looks something like:
Silk Touch
Silk Touch
Silk Touch
Silk Touch
Silk Touch
Silk Touch

**Comment by kwpugh** [comment]
Unforeseen interaction.  Fortunately, easy to fix.  I cannot remove the multiple Silk Touch off the existing pickaxes  though.

**Comment by kwpugh** [comment]
Pushed updates for 1.18.2 and 1.19.2 on Curseforge

**Comment by SomeOldOakTree** [comment]
I appreciate the quick response. Will update to latest version. :)
