### ISSUE TITLE
[1.18.2] New tools for vanilla materials not there?

### ISSUE THREAD

**Issue by CocoManiaDX** [kwpugh/EmeraldTools#35]
Sorry, I just couldn't find any info on this.

The mod page says there's new tools for vanilla materials (gold, iron, diamond, etc), but none of them show up, only the other materials (emerald, obsidian, etc).

Is this something that has to be enabled in the config? If so, I couldn't figure out how.
Or is this something only available for 1.19+?

Thanks in advance, and sorry for the silly question.

**Comment by kwpugh** [comment]
Sorry, those  were added in 1.19.x

**Comment by CocoManiaDX** [comment]
Ah, thank you ^^
