### ISSUE TITLE
Rework Armor balancing

### ISSUE THREAD

**Issue by Kuggle01** [kwpugh/EmeraldTools#36]
I found it strange that Iron, steel and obsidian are all identical barring durability, I think it'd improve the mod alot of they were made more unique, I'd make copper equal to chainmail, Steel can stay as it is but I think the knockback resistance should be removed and I think obsidian armor should have a ton more Knowback resistance, at least the same as netherite

**Comment by kwpugh** [comment]
Frankly, many people have varying opinions about the balancing of the armors (and the tools for that matter).  That is why the config settings exist, which allow you to set many or most of those values to your liking,
