### ISSUE TITLE
[1.20.0] Crossbow upgrades

### ISSUE THREAD

**Issue by Kuggle01** [kwpugh/EmeraldTools#37]
We have upgrades for the regualr bow, but I like crossbows! and having upgrades for bows and not crossbows just makes me feel like their completely obsolete

**Comment by kwpugh** [comment]
Personally, I am not really a fan of the crossbows.  I may look into this though for Minecraft 1.20 or 1.21

**Comment by kwpugh** [comment]
I don't think I'm going to pursue this.
