### ISSUE TITLE
[1.19.2] hammers silk touch budding crystals

### ISSUE THREAD

**Issue by percyV13** [kwpugh/EmeraldTools#38]
If you silk touch hammer a budding amethyst or mod-added budding crystal directly then it'll drop nothing as is intended, however, if you mine one of the blocks next to it so it's caught in the 3x3 area then the budding crystal block will drop as an item.

I'm on Fabric 1.19.2.

**Comment by kwpugh** [comment]
I wasn't aware of this, but I'm not sure I want to restrict it.  Vanilla does not allow for collecting up budding amethyst blocks, for relocation to create a farm.  I kind of like the idea that the hammer will allow for this.

What do you think is the downside for gameplay if allowed, other than the amethyst farming at a location of the player's convenience?

**Comment by kwpugh** [comment]
The funny thing is that, since I wasn't aware of this, I had been playing by traveling back and forth to a nearby geode to collect shards, when I could have broke them and brought them back to my base.

**Comment by kwpugh** [comment]
I assume you might be using MoreGeodes for Fabric as well?

**Comment by kwpugh** [comment]
Fixed in latest release on CurseForge

**Comment by percyV13** [comment]
Didn't see the reply, I personally really like being able to silk touch the budding crystals, particularly the modded ones without an option to make them silk touchable (More Geodes plus the sub-zero and the pink end crystals which I think are both BYG) and I might be grabbing a few more before updating the mod.

But I figured there's probably a server where this would be against the rules or cause problems.

**Comment by kwpugh** [comment]
There are several mods available that specifically add silk touch to budding amethyst and possibly the modded ones and well, might check on Curseforge

**Comment by percyV13** [comment]
Yeah, amethyst is easy and I believe More Geodes has a module, but the BYG ones not so much. Thanks!
