### ISSUE TITLE
Conflict with ores from other mods

### ISSUE THREAD

**Issue by Panduino** [kwpugh/EmeraldTools#4]
In a server, if you change anything in the config file (in my example basic nether ores and enderite), those ores simply stop dropping items. Deleting the config file and not editing it when it comes back fixes this, but is an issue when I want to disable the special tools. Using version 1.1.1

**Comment by kwpugh** [comment]
I'm confused.   When you disable emerald special tools you can't break which ores using which tools?

**Comment by kwpugh** [comment]
I just tried v1.1.1.    Disabled all the special tools in the config and went add broke iron and gold ores with emerald and ruby pickaxes just fine.

**Comment by kwpugh** [comment]
nether ores and enderite breaking may be a problem of mining level, not familiar with those mods

**Comment by kwpugh** [comment]
Ok, I see what it is doing, and I know how to fix it.

**Comment by kwpugh** [comment]
Fixed in v1.1.2
