### ISSUE TITLE
Ordinary tools and enhanced tools can be divided into two parts?

### ISSUE THREAD

**Issue by chen-Futuro** [kwpugh/EmeraldTools#40]
My server players don't like the enhanced tools, maybe they break the balance a bit and don't work well with other mod's weapons like Dragonloot
If possible, I hope that you can separate the four enhancement tools into a new mod
My server is now 1.18.2 Fabric, it will skip 1.19 and update directly to 1.20, I think you can make these changes in 1.20

**Comment by kwpugh** [comment]
you can disable the recipes for those tools with a datapack
