### ISSUE TITLE
No duribality used for hammers

### ISSUE THREAD

**Issue by astocky** [kwpugh/EmeraldTools#43]
Using EmeraldTools-Fabric-1.19.2-1.4.38 with fabric 0.14.11 for minecraft 1.19.2
fabric api fabric-api-0.68.0+1.19.2 and cloth config cloth-config-8.2.88-fabric

When I used hammers no durability is removed when breaking stone.
The tree axes remove durability as normal. Armour and paxels also takes durability damage as normal.

Even if I summon a damaged hammer with: /give @p emerald_tools:emerald_hammer{Damage:1} 1
further mining does no damage.

**Comment by purejosh** [comment]
@astocky Is this still an issue with newer versions? I'm a pretty observant guy, and I haven't noticed this at all. 

Please also post your config file in here, using https://gist.github.com/

**Comment by percyV13** [comment]
I've been having this issue with the most recent version for 1.19.2. If you shift and then mine a single block the durability is used, but if you're mining as normal with the 3x3 area then no durability is used. This has been the case for all the hammers I've tried, I don't think I hit all of them but at least wooden, copper, steel, diamond, and emerald for sure.

**Comment by KuBino122** [comment]
Its still the same no durability. Just infinity durability on hammer when mining 3x3

**Comment by RaptorN64** [comment]
I'm also still getting this issue with infinite durability on both the Hammer (Using 3x3) and the Excavator (Using 3x3), in any/ all ore types. I'm running :

Minecraft 1.19.2
Fabric 0.14.21
cloth-config-8.3.103-fabric
EmeraldTools Fabric 1.19.2-1.4.38

**Comment by kwpugh** [comment]
I fired up a clean install of 1.19.2 and I don't see any problem with the durability.

![Screenshot 2024-02-18 at 3 55 10 PM](https://github.com/kwpugh/emerald_tools_fabric/assets/8809210/469b2461-c125-4235-b2f0-2209f2b441d0)
![Screenshot 2024-02-18 at 3 54 30 PM](https://github.com/kwpugh/emerald_tools_fabric/assets/8809210/d1dd3663-5379-4c94-9ade-2740d163ff01)

**Comment by kwpugh** [comment]
Perhaps the issue was resolved in a later version of Fabric API

**Comment by kwpugh** [comment]
I cannot replicate and everything tests fine on my end.
