### ISSUE TITLE
Configuration of Tools

### ISSUE THREAD

**Issue by ImWhiff** [kwpugh/EmeraldTools#47]
Hello,

I see that I am able to configure tools in the config folder, but I would like if I could configure sword and axe damage separately, as well as configuring attack speed of each separately too. Would it be possible to add those options in the configs?

From my understanding with zero knowledge of modding, I am unable to configure each myself by downloading the source code zip file due to private libs.

**Comment by kwpugh** [comment]
I'm going to go half way on this.  I'm doing to have config options to adjust the sword and axe attack damage, but not the speed.  Reason being, vanilla uses negative numbers for speed internally and it will lead to confusion by players tweaking the values.  This will be added starting with 1.20.6.
