### ISSUE TITLE
[Bug] Steel shovel  crafting recipe doesn't work.

### ISSUE THREAD

**Issue by death-frog** [kwpugh/EmeraldTools#5]
The crafting recipe for the steel shovel is bugged, as there is no way to craft it.
Version 1.2.6
![Steel Shovel Bug](https://user-images.githubusercontent.com/82627223/114963785-7a79e500-9e3b-11eb-8070-77ddcc492961.png)

**Comment by death-frog** [comment]
Version 1.2.6

**Comment by kwpugh** [comment]
Yeah, I messed that one up.   I will fix in 1.2.7

![Screen Shot 2021-04-15 at 9 51 32 PM](https://user-images.githubusercontent.com/8809210/114964694-d5f4a480-9e34-11eb-8072-2fb6f57a1302.png)

**Comment by kwpugh** [comment]
Fixed in 1.2.7.
