### ISSUE TITLE
Custom Enchantments don't work

### ISSUE THREAD

**Issue by FAKHORII** [kwpugh/EmeraldTools#54]
I have another mod that allows me to use multiple incompatible enchantments on an item, ex: protection+ fire protection...etc
I haven't tested it on the armor though, but I have crossbow enchantments on my NORMAL bow, like piercing, multi-shot.. they don't work anymore after upgrading the normal bow to netherite
if there's a way to get over this, would be amazing..
thanks for the mod and thanks for ur time <3

**Comment by kwpugh** [comment]
Could you be more specific about which enchant?  I tried putting Flame on a vanilla bow and upgraded the bow to an Emerald Bow and the Flame worked fine.

**Comment by kwpugh** [comment]
A crossbow enchantment will not work if put on a custom bow, because the code for the crossbow enchant are part of the code in the Crossbow item.
