### ISSUE TITLE
Upgraded bow + infinity enchantment consumes arrows

### ISSUE THREAD

**Issue by cchexcode** [kwpugh/EmeraldTools#56]
The upgraded bow (steel / diamond etc.) consumes arrows despite the bow having the "Infinity" enchantment.

Steps to reproduce:

1. Acquire bow
2. Upgrade bow to steel (or anything else like diamond)
3. Enchant bow with "infinity"
4. Shoot bow and observe arrow count

PS: I love this mod, great work!

**Comment by kwpugh** [comment]
This is being worked on now.

**Comment by kwpugh** [comment]
I've got this coded across Gobber, Emerald Tools, and MoreGems since they use my shared lib for bow code.  I want to do more testing of the new features and config options.  Should be released in a day or so.

**Comment by cchexcode** [comment]
@kwpugh amazing, thanks for the update!

**Comment by kwpugh** [comment]
fixed in latest update on Curseforge

**Comment by cchexcode** [comment]
I have just updated the mod and still observe the same behavior. Bow still consumes arrows if I upgrade it (crafted a new bow, too).

**Comment by kwpugh** [comment]
hmm, I had tested it. And I just checked again, and it does not consume arrows with infinity.

Case you post a current system log so I can see what is going on.

**Comment by cchexcode** [comment]
OK I spun up CurseForge again this evening (2am rn but whatever) and it did show an update for Emeral Tools and Gobber. When I explicitly updated them using the button on the mod list entry (not the update all button), it now works as you described. It must've been an issue with either CurseForge or my Modpack setup. Anyway, consider this closed. Thanks!

**Comment by kwpugh** [comment]
Wonderful.  Enjoy playing.
