### ISSUE TITLE
how do i get to the config

### ISSUE THREAD

**Issue by spiral113** [kwpugh/EmeraldTools#57]
how do i get to the config to edit the stats of the tools

**Comment by kwpugh** [comment]
all of the config file, for all mods that have them, are in the config folder.  The config folder if in the folder where Minecraft is installed on your computer.

**Comment by mpustovoi** [comment]
`…\<your_Minecraft_instance_folder>\config\emerald_tools\emerald_tools_config_settings.json5` for Fabric version

`…\<your_Minecraft_instance_folder>\config\easy-emerald-general.toml` for (Neo)Forge version
