### ISSUE TITLE
It is a Fabric mod and will not work on a vanilla Minecraft Realms

### ISSUE THREAD

**Issue by lildebug** [kwpugh/EmeraldTools#59]
i use plenty of fabric mods on my realm just this one isn't working ?          

    It is a Fabric mod and will not work on a vanilla Minecraft Realms

_Originally posted by @kwpugh in https://github.com/kwpugh/emerald_tools_fabric/issues/58#issuecomment-2381624294_

**Comment by kwpugh** [comment]
do you have fabric api installed on the the realm server?   I guess you are using client side mods.  MY mods are both client and server side mods.   Did you install the mod on the realm server?
