### ISSUE TITLE
Minecraft 1.17 can't open

### ISSUE THREAD

**Issue by Jayjoe4** [kwpugh/EmeraldTools#7]
Hi, I'm trying to play mc on 1.17 fabric and get this error message.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'emerald_tools'!
Exit Code: -1

**Comment by kwpugh** [comment]
Did you update your launcher to use Java 16?

**Comment by kwpugh** [comment]
No response and cannot duplicate.
